spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:postgresql://localhost:5451/postgres
    driverClassName: org.postgresql.Driver
    username: ems-emp
    password: password
  jpa:
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
#      ddl-auto: validate
    open-in-view: false
#  flyway:
#    enabled: true
#    locations: classpath:db/migration


springdoc:
  api-docs:
    path: /api/employee-service/v3/api-docs
  swagger-ui:
    path: /api/employee-service/swagger-ui

server:
  port: 8090
  forward-headers-strategy: framework

